name: Commit Message Conformance

on:
  pull_request: {}

permissions:
  statuses: write
  checks: write
  contents: read
  pull-requests: read

jobs:
  commitmsg-conform:
    uses: cloudbuildlab/actions-commitmsg-conform/.github/workflows/commitmsg-conform.yml@v0
