name: Markdown Lint

on:
  pull_request: {}

permissions:
  statuses: write
  checks: write
  contents: read
  pull-requests: read

jobs:
  markdown-lint:
    uses: cloudbuildlab/actions-markdown-lint/.github/workflows/markdown-lint.yml@v0
